// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuhasibPro.Data.DataContext;

#nullable disable

namespace MuhasibPro.Data.Migrations
{
    [DbContext(typeof(SistemDbContext))]
    [Migration("20260112172302_firstInitialMigration")]
    partial class firstInitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("MuhasibPro.Domain.Entities.SistemEntity.AppVersion", b =>
                {
                    b.Property<string>("CurrentAppVersion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CurrentAppVersionLastUpdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousAppVersiyon")
                        .HasColumnType("TEXT");

                    b.HasKey("CurrentAppVersion");

                    b.ToTable("AppVersiyonlar");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("MuhasibPro.Domain.Entities.SistemEntity.Firma", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adres")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArananTerim")
                        .HasColumnType("TEXT");

                    b.Property<string>("Eposta")
                        .HasMaxLength(75)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmaKodu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<long?>("GuncelleyenId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Il")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ilce")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("KaydedenId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KisaUnvani")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("LogoOnizleme")
                        .HasColumnType("BLOB");

                    b.Property<string>("PBu1")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("PBu2")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostaKodu")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("TCNo")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("TamUnvani")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon1")
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon2")
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<string>("VergiDairesi")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("VergiNo")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("Web")
                        .HasMaxLength(75)
                        .HasColumnType("TEXT");

                    b.Property<string>("YetkiliKisi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Firmalar");
                });

            modelBuilder.Entity("MuhasibPro.Domain.Entities.SistemEntity.Hesap", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArananTerim")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FirmaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<long?>("GuncelleyenId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("KaydedenId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<long>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SonGirisTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Hesaplar");
                });

            modelBuilder.Entity("MuhasibPro.Domain.Entities.SistemEntity.Kullanici", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArananTerim")
                        .HasColumnType("TEXT");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<long?>("GuncelleyenId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("KaydedenId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParolaHash")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Resim")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ResimOnizleme")
                        .HasColumnType("BLOB");

                    b.Property<long>("RolId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Soyadi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Kullanicilar");

                    b.HasData(
                        new
                        {
                            Id = 241341L,
                            Adi = "Ömer",
                            AktifMi = true,
                            ArananTerim = "korkutomer, Ömer Korkut, Yönetici",
                            Eposta = "korkutomer@gmail.com",
                            KaydedenId = 5413300800L,
                            KayitTarihi = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KullaniciAdi = "korkutomer",
                            ParolaHash = "AQAAAAIAAYagAAAAECnYdlrjFiWFJc+FGeGDmvR87uz20oU/Z0K4JE9ddoF2VUnmHw0idEFX8UPOb4cpzQ==",
                            RolId = 1L,
                            Soyadi = "Korkut",
                            Telefon = "0 (541) 330 0800"
                        });
                });

            modelBuilder.Entity("MuhasibPro.Domain.Entities.SistemEntity.KullaniciRol", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArananTerim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<long?>("GuncelleyenId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("KaydedenId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RolTuru")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("KullaniciRoller");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Aciklama = "Sistemin tüm özelliklerine erişim yetkisi.",
                            AktifMi = true,
                            KaydedenId = 5413300800L,
                            KayitTarihi = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RolAdi = "Yönetici",
                            RolTuru = 1
                        });
                });

            modelBuilder.Entity("MuhasibPro.Domain.Entities.SistemEntity.MaliDonem", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArananTerim")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DatabaseType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FirmaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<long?>("GuncelleyenId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("KaydedenId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaliYil")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.ToTable("MaliDonemler");
                });

            modelBuilder.Entity("MuhasibPro.Domain.Entities.SistemEntity.SistemLog", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArananTerim")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<long?>("GuncelleyenId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<long>("KaydedenId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SistemLogs");
                });

            modelBuilder.Entity("MuhasibPro.Domain.Entities.SistemEntity.AppDbVersion", b =>
                {
                    b.HasBaseType("MuhasibPro.Domain.Entities.SistemEntity.AppVersion");

                    b.Property<DateTime>("CurrentDatabaseLastUpdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentDatabaseVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousDatabaseVersion")
                        .HasColumnType("TEXT");

                    b.ToTable("AppDbVersiyonlar");

                    b.HasData(
                        new
                        {
                            CurrentAppVersion = "1.0.0",
                            CurrentAppVersionLastUpdate = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDatabaseLastUpdate = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentDatabaseVersion = "1.0.0",
                            DatabaseName = "Sistem.db"
                        });
                });

            modelBuilder.Entity("MuhasibPro.Domain.Entities.SistemEntity.Hesap", b =>
                {
                    b.HasOne("MuhasibPro.Domain.Entities.SistemEntity.Firma", null)
                        .WithMany("Hesaplar")
                        .HasForeignKey("FirmaId");

                    b.HasOne("MuhasibPro.Domain.Entities.SistemEntity.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("MuhasibPro.Domain.Entities.SistemEntity.Kullanici", b =>
                {
                    b.HasOne("MuhasibPro.Domain.Entities.SistemEntity.KullaniciRol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("MuhasibPro.Domain.Entities.SistemEntity.MaliDonem", b =>
                {
                    b.HasOne("MuhasibPro.Domain.Entities.SistemEntity.Firma", "Firma")
                        .WithMany("MaliDonemler")
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("MuhasibPro.Domain.Entities.SistemEntity.AppDbVersion", b =>
                {
                    b.HasOne("MuhasibPro.Domain.Entities.SistemEntity.AppVersion", null)
                        .WithOne()
                        .HasForeignKey("MuhasibPro.Domain.Entities.SistemEntity.AppDbVersion", "CurrentAppVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MuhasibPro.Domain.Entities.SistemEntity.Firma", b =>
                {
                    b.Navigation("Hesaplar");

                    b.Navigation("MaliDonemler");
                });
#pragma warning restore 612, 618
        }
    }
}
