// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuhasibPro.Data.DataContext;

#nullable disable

namespace MuhasibPro.Data.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260207203010_firstTenantMigration")]
    partial class firstTenantMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("MuhasibPro.Domain.Entities.MuhasebeEntity.DegerlerEntities.AppLog", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArananTerim")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<long?>("GuncelleyenId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<long>("KaydedenId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppLogs");
                });

            modelBuilder.Entity("MuhasibPro.Domain.Entities.MuhasebeEntity.DegerlerEntities.TenantDatabaseVersiyon", b =>
                {
                    b.Property<string>("DatabaseName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CurrentTenantDbLastUpdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentTenantDbVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousTenantDbVersiyon")
                        .HasColumnType("TEXT");

                    b.HasKey("DatabaseName");

                    b.ToTable("TenantDatabaseVersiyonlar");
                });
#pragma warning restore 612, 618
        }
    }
}
